# fly.toml app configuration file generated for hi-mom on 2024-11-07T19:51:44Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hi-mom'
primary_region = 'ord'

[build]
  [build.args]
    GO_VERSION = '1.23.0'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
